### ISSUE TITLE
Cache option individual pages

### ISSUE THREAD

**Issue by grafxflow** [daylightstudio/FUEL-CMS#327]
Hi,

Is there a possibility in future versions to be able to cache individual pages, rather than a clear all?

Or perhaps add the option to the individual edit page?

**Comment by daylightstudio** [comment]
Are you meaning you want to clear the cache while editing a particular page? If so, anytime you save it in the CMS it will clear the cache for just that particular page. Modules are different in that the entire cache gets cleared (because modules can potentially be on any page). Also, you can turn off the cache for a particular page in the CMS in the edit screen (there is a Cache: yes no radio button). 

Alternatively you can turn on off caching all together by adding the following in your fuel/application/config/MY_fuel.php file (default is "cms"):
<code>// Turn on cache. Can be TRUE/FALSE or cms
$config['use_page_cache'] = FALSE;</code>
