### ISSUE TITLE
Build a simple multi-tenant websites

### ISSUE THREAD

**Issue by casaca** [daylightstudio/FUEL-CMS#375]
I would like to refer to this project to build a simple multi-tenant SaaS products. Can you give some idea?

**Comment by daylightstudio** [comment]
FUEL uses MySQL exclusively so you won't be able to take advantage of say something like Postgres schemas. So that leaves you with really one other option and that is to create new databases for each tenant. The latter can be done by changing the database in the fuel/application/config/database.php config perhaps based on a the subdomain. That will handle the data, however if you are needing to also have different static view files, blocks, layouts, config, etc, then it's best to just create separate application folders for each tenant and specify the path to their application folder in the main index.php bootstrap file.
