### ISSUE TITLE
Form submission with image upload not working when CSRF enabled

### ISSUE THREAD

**Issue by developer-ec** [daylightstudio/FUEL-CMS#409]
Hi FUEL-CMS Team,

I have encountered this error when the CSRF enabled.

After submitting the form with image, there's an error displaying:

**The action you have requested is not allowed.**

But when you submit the form without selecting the image to be uploaded, the submission is successful. Maybe there's a conflict in the CSRF token between the "Upload Asset" and form submit.

Hoping for your immediate response. Thank you! :)

**Comment by daylightstudio** [comment]
Please provide steps to replicate the error. Thanks.

**Comment by developer-ec** [comment]
Hi FUEL-CMS Team,

Here are the steps:

1. Enable CSRF in the application/config/config.php
$config['csrf_protection'] = TRUE;

In my simple module,

1. Click for "Create" button in module index page.
2. Fill up the form and click for "Upload Asset" button then select for the image to be uploaded.
3. Click the "Save" button.
4. After clicking the "Save" button, there's an error message displayed: "The action you have requested is not allowed."

The issue only occurred once you have clicked for "Upload Asset" button and select for an image.

Thank you for your immediate response! :)

**Comment by daylightstudio** [comment]
What version of FUEL are you running (fuel/modules/fuel/config/fuel_constants.php has it at the top as the constant FUEL_VERSION)?

**Comment by developer-ec** [comment]
I'm using the version 1.4

**Comment by daylightstudio** [comment]
I wasn't able to consistently replicate the issue. However, I did see one thing where the query string parameters weren't being completely replicated on redirect. When I changed the order of the query string parameters so that the "uploaded_file_name" was at the end of the query string it seemed to be more consistent and have a hunch that it may be related to the file name being in the query string. I've posted a potential fix to test out on your end in the develop branch.
