### ISSUE TITLE
Docs, Forum and Wiki

### ISSUE THREAD

**Issue by marcus-at-localhost** [daylightstudio/FUEL-CMS#572]
As much as I like the Fuel CMS Docs in how extensive they are, they often miss key details that maybe expect too much knowledge of the CMS interior from the developer or were added later.[1]

It's also hard to maintain the docs with all the html or to contribute (even if the system is quite clever).[2]

What do you think about using Githubs Wiki to add and curate user submitted solutions and code snippets that might help people a bit more to understand the power of Fuel CMS?

Another pain point for me is the forum. There is so much good information but often it's hard to find or worse, hard to read, because it's missing proper code fencing and there is no syntax highlighting. Sometimes I wish I could go in and just add some ``` to make it at least readable...
Maybe Github own discussion forum could be a possibility[3]? I know that would fracture everything even more, but I think it could save you time from maintaining your own forum software and spend some on overhauling the docs. And maybe more people would contribute?

Just thoughts :) I know this needs resources to do it...

best, m.

[1] I was wondering why my block layout fields <https://docs.getfuelcms.com/general/layouts#layouts_block_layouts> in a simple module didn't display any previously saved data. Turns out I had to set a model... a common concept in Fuel CMS, but it's easy to get lost in all the possibilities

```
$products['key_value_table'] = new Fuel_block_layout('key_value_table');
$products['key_value_table']->set_label('Tabelle');
// Set Model in case you query data from a module.
$products['key_value_table']->set_model('Products_model');
```

[2] it should be possible to generate a bunch of markdown alternatively and slowly move over to markdown or reStructured text or whatever?!

[3] It seems it's still in beta but one can request access here: https://github.community/t/can-one-apply-for-github-discussions-beta/121120/161 ?!

**Comment by daylightstudio** [comment]
Thanks for sharing your ideas and current frustrations. There are a number of things we would like to do to improve FUEL CMS, however, as you probably guessed, we just don't have the resources at the moment to make those types of changes. The original documentation took months of time in between other projects and I would estimate a transition to another platform plus a new forum would also be pretty significant. I would say more importantly, the core of FUEL CMS, CodeIgniter, is now at version 4, which is a great improvement, but completely incompatible and would require a complete rewrite (which I briefly attempted a couple years ago, but abandoned after coming to terms with the pace of speed of CI4 development). The CodeIgniter team has said they will support version 3 for the foreseeable future, which is great, but will likely mean any significant updates to CodeIgniter will be on 4 alone.

FUEL CMS is over 10 years old and showing its age. That's tough to say since it was a passion project for so long. Right now we are committed to keeping the current version working with minor updates and security fixes.

**Comment by marcus-at-localhost** [comment]
Do you keep using Fuel CMS for your own projects?

Personally I think there is no reason to move to CI 4, just make sure that CI 3 works on future php versions.
Sure there are more modern approaches and coding paradigms, but as long as composer works, everything should be fine and can be updated step by step. Maybe I'm wrong.

I would be more concerned about the backend javascript stuff, but even that is manageable. I like that I don't need a build process to extend functionality in the backend, it's easy to overwrite stuff. Maybe jquery Ui is outdated, but that's it.

Anyways, I guess I just write down my findings for myself and share it if needed :).

**Comment by daylightstudio** [comment]
We have built a lot of projects on FUEL CMS and so there are a number of projects we are actively updating and maintaining. New projects, less so these days.

**Comment by marcus-at-localhost** [comment]
Can you share what you are using now? What I value most in Fuel CMS is the integration of existing databases and how flexible I can manage and interact with them. I haven't found another system in that regard. I do struggle a bit with the decision to build on Fuel for a new project at least in parts.

Sorry that's a bit off-topic here :).

**Comment by daylightstudio** [comment]
For us, it really depends on the project and the client's expectations and some clients are particular about their CMS or they are coming from an existing CMS that we need to integrate with. More often these days that means something other than FUEL CMS. For some of our newer projects, we've been using [CraftCMS](https://craftcms.com/) because it is built on top of the Yii framework (similar to FUEL being on top of CodeIgniter) which I like and the community is more programming oriented I feel. However, we've also been building more with Laravel which has us looking more at [Statamic 3](https://statamic.dev/) that just came out which and is now just Composer package and doesn't require a database at all so everything is in version control (no syncing DBs between environments). Laravel also has [Nova](https://nova.laravel.com/) which is a way to spin up admin interfaces on your projects but we've only really played around with that too. All three are commercial applications.

That said, although the power and flexibility of Laravel is great, it's not as easy as to setup and wrap your head around as CodeIgniter which has always hit a sweet spot for me (and I think CI 4 has done a great job of modernizing without breaking from the CI spirit). I've always preferred building my projects in code that I own, completely understand and can fix/update immediately should an issue arise but there is a definite trade-off in doing that which has required us to branch out and understand more of the other options out there... other than Wordpress (which we do use too, but only if the project really makes sense to use it). I hope that helps.

**Comment by marcus-at-localhost** [comment]
Thanks for the inspiration. Statamic was new to me and reminds me a bit of KirbyCMS. I was about to look into CraftCMS as well. I think what turns me off of Laravel are the fast update cycles that might leaves apps aging even faster.
I'm with you, regarding CI. Anyways - thanks again for the insight!

**Comment by marcus-at-localhost** [comment]
Just in case someone needs this info - While Nova has no way to try before buy a licence, there is also https://backpackforlaravel.com/ which is a similar Admin Panel and you can try it locally without a licence. I'm checking out the docs and a lot reminds me of FUEL (minus the CMS which I still like) https://backpackforlaravel.com/docs/4.1/crud-fields 

I might go forward with FUEL anyway because I know it better.
