### ISSUE TITLE
Start file missing on FUEL_CMS 1.4.1 

### ISSUE THREAD

**Issue by 3ct0s** [daylightstudio/FUEL-CMS#577]
Hi There,

I acknowledge the fact that this version is not the latest and greatest but I need this specific one.
Once I finished the set-up process a went ahead on the http://IP/fuelcms/fuel/start the file does not exist (404). And yes I have admin_enabled on MY_fuel.php

Can anyone help?
Thanks.

**Comment by daylightstudio** [comment]
Did you update your .htaccess file to the following since you have it in a fuelcms subfolder?
```
RewriteBase /fuelcms/
```

**Comment by 3ct0s** [comment]
Yes I did, but I am still getting 404 on /fuelcms/fuel/start
What else can I do?

**Comment by daylightstudio** [comment]
Does `/fuelcms/index.php/fuel/login` and`/fuelcms/fuel/login` work? If it doesn't recognize the latter, it sounds like an Apache configuration issue where it's not recognizing the mod_rewrite rules.

**Comment by 3ct0s** [comment]
Ok so http://192.168.10.132/fuelcms/fuel/login does not work 
But http://192.168.10.132/fuelcms/index.php/fuel/login does work and when I enter admin admin the dashboard does not load.

**Comment by 3ct0s** [comment]
I have to add index.php to every request, how do I fix that?

**Comment by daylightstudio** [comment]
Not necessarily. If the above works with index.php but it doesn't without it, it sounds like it may be an Apache mod_rewrite issue on the server which FUEL is initially setup to work with. There is a CodeIgniter file at `fuel/application/config/config.php` that has a configuration key of 'index_page' which is blank but you can add 'index.php' so that the URLs will work.

**Comment by 3ct0s** [comment]
After I changed that it finally worked, thank you for your help!
